// Generated by tools/bakeFont -- do not hand-edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace HackAtlas
{
inline constexpr int kCellWidth = 11;
inline constexpr int kCellHeight = 21;
inline constexpr int kBytesPerRow = 2;
inline constexpr int kBytesPerGlyph = kBytesPerRow * kCellHeight;
inline constexpr std::size_t kGlyphCount = 97;

struct Glyph
{
    char32_t codepoint;
    const uint8_t* bits; // kBytesPerGlyph bytes, row-major, MSB-first, 1 = ink
};

extern const Glyph kGlyphs[kGlyphCount];

} // namespace HackAtlas
