// Generated by tools/offline/bakeFont -- do not hand-edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace HackAtlas
{

struct Glyph
{
    char32_t codepoint;
    const uint8_t* bits; // Atlas::bytesPerGlyph bytes, row-major, one byte per
                         // pixel: 0 = no ink, 255 = full ink (grayscale coverage,
                         // i.e. an alpha value -- see Canvas::blitGlyph)
};

struct Atlas
{
    int cellWidth;
    int cellHeight;
    int bytesPerRow;
    int bytesPerGlyph;
    std::size_t glyphCount;
    const Glyph* glyphs;
};

inline constexpr std::size_t kAtlasCount = 9;
extern const Atlas kAtlases[kAtlasCount]; // sorted ascending by cellWidth

} // namespace HackAtlas
