// canvas.h -- fj's own software rasterizer: the only way core code draws
// pixels. It's what src/cursor.cpp and src/cardItem.cpp's draw methods get
// rewritten against, and what the future RowItem replacement draws text
// through.
//
// Deliberately minimal, derived from what those files actually draw today
// (see PLAN_addendum.md), not a general 2D API: fillRect, fillTriangle,
// line (built from two filled triangles -- see canvas.cpp), and glyph/text
// drawing from the baked Hack atlas (hackAtlas.h). Glyphs ARE anti-aliased
// (tools/offline/bakeFont bakes a grayscale coverage byte per pixel, and
// blitGlyph alpha-blends it via blendRect) -- but the primitive shapes
// (fillTriangle, line) are still hard-edged, no rounded corners, no line
// caps, no clip regions beyond the canvas bounds, all deferred the same
// way non-blocky primitive-shape scaling was.
//
// Canvas works entirely in pixel (_view) coordinates. Converting from the
// scene's inch-based coordinate system (_scen -- see PLAN.md's
// "Coordinate System" section) is the caller's job, not this header's.

#pragma once

#include "platform.h"

#include <cstdint>
#include <span>
#include <vector>

struct Point
{
    int x{0};
    int y{0};
};

struct Rect
{
    int x{0};
    int y{0};
    int w{0};
    int h{0};
};

namespace HackAtlas
{
struct Glyph;
struct Atlas;
}

// Given a ladder of baked atlases (HackAtlas::kAtlases, generated by
// tools/offline/bakeFont -- see resources/hackAtlas.h), returns whichever
// has the cellWidth closest to desiredCellWidth_px. Hand-written, not
// generated: which atlas to use is a runtime rendering decision, not
// baked data. There are only a handful of atlases (one per Windows
// display-scale step), so a linear scan is all this needs.
const HackAtlas::Atlas& pickAtlas(int desiredCellWidth_px);

class Canvas
{
  public:
    // atlas is the one this Canvas draws glyphs from for its whole
    // lifetime (a Canvas is one rendered frame -- see main.cpp -- and a
    // frame is drawn with exactly one atlas). Stored as a pointer, not a
    // reference, purely so Canvas keeps ordinary (if never-used) copy/move
    // assignment; the constructor takes a reference to document that it's
    // never null.
    Canvas(int width_px, int height_px, const HackAtlas::Atlas& atlas);

    int width() const { return m_width; }
    int height() const { return m_height; }

    // Matches PlatformWindow::present()'s signature directly:
    //   window.present(canvas.pixels(), canvas.width(), canvas.height());
    std::span<const Pixel> pixels() const { return m_pixels; }

    void fillRect(Rect rect, Pixel color);
    void fillTriangle(Point p0, Point p1, Point p2, Pixel color);

    // Blends color into the pixels already under rect, weighted by alpha
    // (0 = rect unchanged, 255 = identical to fillRect). blitGlyph uses
    // this to draw anti-aliased glyph edges from the atlas's coverage
    // bytes instead of a hard-edged block; public because it's a genuine,
    // reusable primitive now, not just glyph-drawing internals.
    void blendRect(Rect rect, Pixel color, int alpha);

    // A filled quad along the segment; no rounded caps (see the header
    // comment -- same deferred-polish precedent as font scaling).
    void line(Point p0, Point p1, Pixel color, int thickness);

    // Looks up codepoint in this Canvas's atlas and blits it at pos,
    // scaled by an integer factor (2 for Title rows reusing the Body
    // atlas's own bitmaps, per PLAN_addendum.md -- everything else always
    // passes 1; window-fit scaling is pickAtlas's job now, not this
    // parameter's). Silently no-ops if codepoint isn't baked -- there are
    // only 97 of them (ASCII 0x20-0x7E plus the two link arrows
    // CardItem::linkStr() uses).
    void drawChar(char32_t codepoint, Point pos, Pixel color, int scale = 1);

    // Draws each codepoint left-to-right, advancing by the atlas cell
    // width per character -- fj is fixed-pitch-only, so this is genuinely
    // just repeated drawChar. Takes decoded codepoints rather than a
    // UTF-8/QString byte sequence so this header doesn't need an opinion
    // on string encoding; that's the core model's call (phase 3), not the
    // renderer's.
    void drawText(std::span<const char32_t> text, Point pos, Pixel color, int scale = 1);

  private:
    void blitGlyph(const HackAtlas::Glyph& glyph, Point pos, Pixel color, int scale);

    int m_width;
    int m_height;
    const HackAtlas::Atlas* m_atlas;
    std::vector<Pixel> m_pixels;
};
